### ISSUE TITLE
Improve detection of files that need to be linted

### ISSUE THREAD

**Issue by j2kun** [j2kun/chktex-action#3]
See if I can have a pull request workflow that runs lint only on the .tex files that are edited in the pull request.

**Comment by j2kun** [comment]
Also add a workflow that runs on any push that lints every .tex file in the repository.  (probably a simple `find | xargs chktex-q`)

**Comment by j2kun** [comment]
Looks like I can maybe get it from the GITHUB_EVENT_PATH env var shown by Jess here

https://blog.jessfraz.com/post/the-life-of-a-github-action/

And seems to be documented in the webhooks here: https://developer.github.com/webhooks/#events

Need to figure out what in the payload content can tell me what files were changed in the PR

**Comment by j2kun** [comment]
Looks like https://developer.github.com/v3/pulls/#list-pull-requests-files

And I can 

`GET /repos/:owner/:repo/pulls/:pull_number/files`

Look for the status field and ensure it's not removed (what is the exact string there?), and then deal with pagination. Maybe time to drop to a python API client...

[
  {
    "sha": "bbcd538c8e72b8c175046e27cc8f907076331401",
    "filename": "file1.txt",
    "status": "added",
    "additions": 103,
    "deletions": 21,
    "changes": 124,
    "blob_url": "https://github.com/octocat/Hello-World/blob/6dcb09b5b57875f334f61aebed695e2e4193db5e/file1.txt",
    "raw_url": "https://github.com/octocat/Hello-World/raw/6dcb09b5b57875f334f61aebed695e2e4193db5e/file1.txt",
    "contents_url": "https://api.github.com/repos/octocat/Hello-World/contents/file1.txt?ref=6dcb09b5b57875f334f61aebed695e2e4193db5e",
    "patch": "@@ -132,7 +132,7 @@ module Test @@ -1000,7 +1000,7 @@ module Test"
  }
]

**Comment by j2kun** [comment]
Got the python api and can get the pull request files info using 

https://pygithub.readthedocs.io/en/latest/examples/PullRequest.html#get-pull-request-by-number

**Comment by audio-engineer** [comment]
@j2kun I am working on this

**Comment by audio-engineer** [comment]
I added pull request file annotations and review request changes/approval on my `dev` branch. PR will be opened in the coming days
