### ISSUE TITLE
Tag the latest merge commit

### ISSUE THREAD

**Issue by audio-engineer** [j2kun/chktex-action#38]
@j2kun

Kindly tag https://github.com/j2kun/chktex-action/commit/a3f031bbc2e5899f2b3efddcf9fc9ed25d525b98 as `v2.1.0`. Also, tag it as `v2`.

Next time a PR gets merged, move the `v2` tag to the new merge commit. I know this is counterintuitive, but this works best for GitHub Actions, so users can benefit from "rolling release" versioning by referencing the action with `j2kun/chktex-action@v2`.

**Comment by j2kun** [comment]
Done, though I'm not sure if I need to create `v2` as part of a GH release to make this work. So far I create `v2.1.0` as a release and manually added the `v2` tag to point to the same commit.

**Comment by audio-engineer** [comment]
@j2kun

It is indeed necessary to create a `v2` tag and move it to the latest commit on every merge. This is because the GitHub workflow `@` syntax requires an explicit reference, i.e., in `j2kun/chktex-action@v2` the `v2` points to the `v2` tag that you just created. Without tagging the latest commit as `v2`, users can only reference the action as `j2kun/chktex-action@v2.1.0`. So on each merge/update of the action, all users have to manually change the reference in the workflow e.g. to `j2kun/chktex-action@v2.2.0`. This is cumbersome because it also means that users have to manually check the repository for changes, since there is no Actions package manager that can bump the version.
By moving the `v2` tag, users can just reference the action as `j2kun/chktex-action@v2` and when the action receives an update, the next time the workflow runs it will download the latest source code.
Should a user still wish to explicitly lock to a specific version, they can still do that.

Also, releases are not strictly necessary. They are more of a pretty "newsletter" for users; an interface through which users can get information about the latest changes in the repository. Tags still determine the actual versioning of code/Actions. I am not sure if GitHub has an interface for moving tags. You probably have to do it using the `git` CLI moving forward.

Read more here: https://docs.github.com/en/actions/sharing-automations/creating-actions/about-custom-actions#using-tags-for-release-management

Especially this bit:

<img width="762" alt="image" src="https://github.com/user-attachments/assets/b1cf6998-d15d-4245-829d-099ca9ac62f8">
